#!/bin/bash


. setenv-local

shaders_dir=./dali-core/dali/graphics/vulkan/shaders
generated_dir=./dali-core/dali/graphics/vulkan/generated

shaders="
${shaders_dir}/basic-shader.vert|VSH_CODE|vert
${shaders_dir}/basic-shader.frag|FSH_CODE|frag"

echo "// Autogenerated" > ${generated_dir}/spv-shaders-gen.h
echo -e "#ifndef SPV_GENERATED_HEADER
#define SPV_GENERATED_HEADER
#include <vector>\n#include <cstdint>\n\n" >> ${generated_dir}/spv-shaders-gen.h

echo "// Autogenerated" > ${generated_dir}/spv-shaders-gen.cpp
echo "#include \"spv-shaders-gen.h\"" > ${generated_dir}/spv-shaders-gen.cpp
echo "#pragma GCC diagnostic push
#pragma GCC diagnostic ignored \"-Wlarger-than=\"" >> ${generated_dir}/spv-shaders-gen.cpp

for f in ${shaders} ; do
    fname=$(echo $f | awk -F '|' '{print $1}')
    varname=$(echo $f | awk -F '|' '{print $2}')
    stagename=$(echo $f | awk -F '|' '{print $3}')
    out=/tmp/$(basename ${fname}).spv
    ${VULKAN_SDK}/bin/glslangValidator -V1.0 -S ${stagename} ${fname} -o ${out}
    echo "std::vector<uint8_t> $varname = {" >> ${generated_dir}/spv-shaders-gen.cpp
    xxd -i ${out} | tail -n +2 | head -n -2 >> ${generated_dir}/spv-shaders-gen.cpp
    echo "};" >> ${generated_dir}/spv-shaders-gen.cpp
    echo "extern std::vector<uint8_t> $varname;" >> ${generated_dir}/spv-shaders-gen.h

    echo "/*" >> ${generated_dir}/spv-shaders-gen.h
    cat $fname >> ${generated_dir}/spv-shaders-gen.h
    echo -e "*/\n\n" >> ${generated_dir}/spv-shaders-gen.h

done

echo "#pragma GCC diagnostic pop" >> ${generated_dir}/spv-shaders-gen.cpp

echo -e "#endif // SPV_GENERATED_HEADER\n\n" >> ${generated_dir}/spv-shaders-gen.h





